# 文件名建议统一为 pull-request.yml 
# 应用 test-build.yml 的 demo

name: MAIN_PULL_REQUEST

on:
  pull_request:
    branches: [develop, main, compositionAPI]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/cache@v4
        env:
          cache-name: cache-nodemodules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm install

      - name: Build 
        run: npm run build